services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_admin_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_fatec
      MYSQL_PASSWORD: admin_password
    volumes:
      - db_data:/var/lib/mysql 

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user_fatec
      WORDPRESS_DB_PASSWORD: admin_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
