name: Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Define a versão do Node.js (ajuste se necessário)
          cache: 'npm'       # Ativa o cache para acelerar a instalação das dependências

      - name: Instalar dependências
        run: npm ci          # Instala as dependências de forma limpa e rápida baseada no package-lock.json

      - name: Executar testes (Jest)
        run: npm test        # Executa o comando de teste definido no seu package.json

      - name: Verificar index.html
        run: |
          test -f index.html
          echo "index.html encontrado!"

      - name: Verificar Dockerfile
        run: |
          test -f Dockerfile
          echo "Dockerfile encontrado!"

  build:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pipeline-ci:latest
